### ISSUE TITLE
Some generated DICOM files can't be read in Eclipse

### ISSUE THREAD

**Issue by ant0nsc** [microsoft/InnerEye-DICOM-RT#5] opened 2022-03-16 09:16 UTC
reported by @furtheraway: Varian's eclipse software can't read some DICOM files output by InnerEye.

Pre-processing the files with Dicom+ helps.

**Comment by peterhessey** [comment] 2022-05-19 13:39
Duplicate of #6

**Closed as completed by peterhessey** 2022-05-19 13:39 UTC
Labels: duplicate
